# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8973133f49bba14c51f9fd507d38f686cb7823f77901a3a9f87c43527289555ac68ac76d46d319286f8ac6b16fceb03ad0a1d25b2767a0677c9d4cb81063afb

test:
  secret_key_base: e0d443a67f85b9479578f8493324f1a67002089ff37d4bdec9bdaeae7985bd0cdf33d79121bd5d79f3b81fe57fb9d5383d68fd4a795bab19670ad71282ac075d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
